# Tratamento de Dados

In [169]:
import pandas as pd

# Bibliotecas de visualização
import matplotlib.pyplot as plt


# Importando modelos do SciKit-Learn
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier 
from sklearn import tree
from sklearn.linear_model import LogisticRegression

# Importando Matrix de Confusão.
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import confusion_matrix

# Importando acuracy score
from sklearn.metrics import accuracy_score

# Importando score de precisão
from sklearn.metrics import precision_score

# Importando o Recall Score
from sklearn.metrics import recall_score

In [170]:
df = pd.read_csv('../train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [171]:
print('qtd AGE:', df.Age.count())
print(891-714)

qtd AGE: 714
177

In [172]:


def tratamentoDaBase(base):
    # base = base.drop('Cabin', axis=1)
    colunas = base.dtypes[base.dtypes.values == 'str'].index
    base = base.drop(colunas, axis=1)
    base = base.dropna()

    return base

df = tratamentoDaBase(df)
df.count() # Teste com 714 registros

PassengerId    714
Survived       714
Pclass         714
Age            714
SibSp          714
Parch          714
Fare           714
dtype: int64

# Avaliando o modelo

In [173]:
# Separando dados de treino e teste
X = df.drop('Survived', axis=1)
y = df.Survived

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=.2, random_state=42)

In [174]:
def classificacao_modelos(X_treino, X_teste, y_treino, y_teste):
    neigh = KNeighborsClassifier(n_neighbors=3).fit(X_treino, y_treino)
    dtree = tree.DecisionTreeClassifier(random_state=0).fit(X_treino, y_treino)
    logistic = LogisticRegression(random_state=0, max_iter=1000).fit(X_treino, y_treino)

    pred_knn = neigh.predict(X_teste)
    pred_tree = dtree.predict(X_teste)
    pred_log = logistic.predict(X_teste)

    # Acurácia
    print('Acurácia dos modelos')
    print('KNN:', accuracy_score(y_teste, pred_knn))
    print('Árvore de Decisão', accuracy_score(y_teste, pred_tree))
    print('Regressão Logistica', accuracy_score(y_teste, pred_log))
    print('\n')

    # Precisão
    print('Precisão dos Modelos')
    print('KNN: ', precision_score(y_teste, pred_knn))
    print('Árvore de Decisão: ', precision_score(y_teste, pred_tree))
    print('Regressão Logística: ', precision_score(y_teste, pred_log))
    print('\n')
    
    # Recall
    print('Recall dos Modelos')
    print('KNN: ', recall_score(y_teste, pred_knn))
    print('Árvore de Decisão: ', recall_score(y_teste, pred_tree))
    print('Regressão Logística: ', recall_score(y_teste, pred_log))
    print('\n')

In [175]:
classificacao_modelos(X_treino, X_teste, y_treino, y_teste)

Acurácia dos modelos
KNN: 0.6223776223776224
Árvore de Decisão 0.6643356643356644
Regressão Logistica 0.6993006993006993


Precisão dos Modelos
KNN:  0.5238095238095238
Árvore de Decisão:  0.5909090909090909
Regressão Logística:  0.6666666666666666


Recall dos Modelos
KNN:  0.39285714285714285
Árvore de Decisão:  0.4642857142857143
Regressão Logística:  0.4642857142857143

In [176]:
df

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
885          886         0       3  39.0      0      5  29.1250
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[714 rows x 7 columns]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Survived</th>
      <th>Pclass</th>
      <th>Age</th>
      <th>SibSp</th>
      <th>Parch</th>
      <th>Fare</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>3</td>
      <td>22.000000</td>
      <td>1</td>
      <td>0</td>
      <td>7.2500</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>1</td>
      <td>38.000000</td>
      <td>1</td>
      <td>0</td>
      <td>71.2833</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>3</td>
      <td>26.000000</td>
      <td>0</td>
      <td>0</td>
      <td>7.9250</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>1</td>
      <td>35.000000</td>
      <td>1</td>
      <td>0</td>
      <td>53.1000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>3</td>
      <td>35.000000</td>
      <td>0</td>
      <td>0</td>
      <td>8.0500</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>886</th>
      <td>0</td>
      <td>2</td>
      <td>27.000000</td>
      <td>0</td>
      <td>0</td>
      <td>13.0000</td>
    </tr>
    <tr>
      <th>887</th>
      <td>1</td>
      <td>1</td>
      <td>19.000000</td>
      <td>0</td>
      <td>0</td>
      <td>30.0000</td>
    </tr>
    <tr>
      <th>888</th>
      <td>0</td>
      <td>3</td>
      <td>29.699118</td>
      <td>1</td>
      <td>2</td>
      <td>23.4500</td>
    </tr>
    <tr>
      <th>889</th>
      <td>1</td>
      <td>1</td>
      <td>26.000000</td>
      <td>0</td>
      <td>0</td>
      <td>30.0000</td>
    </tr>
    <tr>
      <th>890</th>
      <td>0</td>
      <td>3</td>
      <td>32.000000</td>
      <td>0</td>
      <td>0</td>
      <td>7.7500</td>
    </tr>
  </tbody>
</table>
<p>891 rows × 6 columns</p>
</div>

## Eliminando variáveis com alta cardinalidade

In [177]:
df.columns.duplicated().any()

np.False_

In [178]:
df = pd.read_csv('../train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [179]:
# Substituição de valores nulos pela média .
def tratamento2DaBase(base):
    base.loc[base.Age.isnull(), 'Age'] = base['Age'].mean()
    base = base.drop('PassengerId', axis=1)
    colunas = base.dtypes[base.dtypes.values == 'str'].index
    base = base.drop(colunas, axis=1)
    # base = base.dropna()

    return base

df = tratamento2DaBase(df)
display(df.count()) # Teste com 891 registros.
df

Survived    891
Pclass      891
Age         891
SibSp       891
Parch       891
Fare        891
dtype: int64

     Survived  Pclass        Age  SibSp  Parch     Fare
0           0       3  22.000000      1      0   7.2500
1           1       1  38.000000      1      0  71.2833
2           1       3  26.000000      0      0   7.9250
3           1       1  35.000000      1      0  53.1000
4           0       3  35.000000      0      0   8.0500
..        ...     ...        ...    ...    ...      ...
886         0       2  27.000000      0      0  13.0000
887         1       1  19.000000      0      0  30.0000
888         0       3  29.699118      1      2  23.4500
889         1       1  26.000000      0      0  30.0000
890         0       3  32.000000      0      0   7.7500

[891 rows x 6 columns]

In [180]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Age       891 non-null    float64
 3   SibSp     891 non-null    int64
 4   Parch     891 non-null    int64
 5   Fare      891 non-null    float64
dtypes: float64(2), int64(4)
memory usage: 41.9 KB

In [181]:
# Separando dados de treino e teste
X = df.drop('Survived', axis=1)
y = df.Survived

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=.2, random_state=42)

In [182]:
classificacao_modelos(X_treino, X_teste, y_treino, y_teste)

Acurácia dos modelos
KNN: 0.664804469273743
Árvore de Decisão 0.6424581005586593
Regressão Logistica 0.7318435754189944


Precisão dos Modelos
KNN:  0.6346153846153846
Árvore de Decisão:  0.5806451612903226
Regressão Logística:  0.7708333333333334


Recall dos Modelos
KNN:  0.44594594594594594
Árvore de Decisão:  0.4864864864864865
Regressão Logística:  0.5

[Teste dos modelos](evolucao_de_testes_dos_modelos.xlsx)


# Teste 4 891 registros

## Acurácia dos modelos
* KNN: 0.664804469273743
* Árvore de Decisão: 0.6424581005586593
* Regressão Logistica: 0.7318435754189944


## Precisão dos Modelos
* KNN:  0.6346153846153846
* Árvore de Decisão:  0.5806451612903226
* Regressão Logística:  0.7708333333333334


## Recall dos Modelos
* KNN:  0.44594594594594594
* Árvore de Decisão:  0.4864864864864865
* Regressão Logística:  0.5


# teste 2 eliminando alta cardinalidade	
## Acurácia	
* KNN:	0.586592179
* Árvore de Decisão:	0.670391061
* Regressão Logistica:	0.731843575
## Precisão	
* KNN:	0.5
* Árvore de Decisão:	0.592592593
* Regressão Logistica:	0.770833333
## Recall	
* KNN:	0.351351351
* Árvore de Decisão:	0.648648649
* Regressão Logistica:	0.5